### ISSUE TITLE
Can't Use Setting at Pebble Steel

### ISSUE THREAD

**Issue by nsicko42** [lfhbento/timeboxed-watchface#17]
The application has been successfully installed and is well visible to Pebble, but the settings are not available.

```
app version 5.0
pebble steel firmware version 3.12.3 (up-to-date)
```

**Comment by lfhbento** [comment]
Hi! Thanks for reporting this! To help me troubleshoot: Are you on Android or iOS? A couple of people reported it not installing properly. Is it installing in your case then? If so, are you seeing a blank screen then?

**Comment by nsicko42** [comment]
I am using Android Nugat 7.1 on the Samsung Galaxy Note 8. I can not see any more reported issues because I can not find anyone using Pebble Steel around.
In my case, I installed the update from 4.5 and I deleted and reinstalled the app because the settings were not displayed. After that, only the clock and date are displayed, and nothing else is displayed. Of course, you will not be able to use the settings after reinstalling the app.

**Comment by lfhbento** [comment]
And when you try to open the settings, is it just a blank white screen?

**Comment by nsicko42** [comment]
No. It display watch face selection again.
So even if I tap the setting button, nothing changes on the watch face selection screen. It looks like a watch face without settings.

**Comment by lfhbento** [comment]
Hi! I've released version 5.1 that hopefully addresses the issue. Let me know if it works! I'll try to find an android device to test this :P

**Comment by nsicko42** [comment]
Hi! I reinstall app for update to version 5.1. For now, there is a change in the screen. yeah!!

But it only displays a black screen unfortunately. And my phone was very slow while the black screen that looks like timeboxed setting screen is floating. It seems to be in an infinite loop.

I look forward to find android to fix this up. :)

**Comment by nsicko42** [comment]
I've had similar problems with other apps.
The app had problems adding health features. I've done reporting, and the app creator has modified it to show the settings, but there's still another bug and the app creator has not solved the problem yet.
The bug is that the setting does not apply at all.

I hope this is a hint to solve this problem.

**Comment by lfhbento** [comment]
Thanks for the tip! For now I've rolled back 5.0 and 5.1, so you should see 4.5 again. That will give me some time to work on a fix without breaking people's watchfaces :)

**Comment by lfhbento** [comment]
I fixed the issue with Android phones :) All good now
